---
title: "Homework#4"
author: "Hertz Casseus"
date: "10/14/2020"
output: html_document
---
## Homework 4
## Group Members: Fareha and Neshma 


load("acs2017_ny_data.RData")
attach(acs2017_ny)
use_varb <- (AGE >= 25) & (AGE <= 55) & (LABFORCE == 2) & (WKSWORK2 > 4) & (UHRSWORK >= 35)
dat_use <- subset(acs2017_ny,use_varb) # 
detach()
attach(dat_use)

model_temp1 <- lm(INCWAGE ~ AGE + female + AfAm + Asian + Amindian + race_oth + Hispanic + educ_hs + educ_somecoll + educ_college + educ_advdeg)
summary(model_temp1)

Call:
  lm(formula = INCWAGE ~ AGE + female + AfAm + Asian + Amindian + 
       race_oth + Hispanic + educ_hs + educ_somecoll + educ_college + 
       educ_advdeg)

Residuals:
  Min      1Q  Median      3Q     Max 
-148088  -33205  -10708   13053  625543 

Coefficients:
  Estimate Std. Error t value Pr(>|t|)    
(Intercept)    -7096.25    2446.71  -2.900 0.003730 ** 
  AGE             1316.69      39.66  33.199  < 2e-16 ***
  female        -24939.46     720.43 -34.617  < 2e-16 ***
  AfAm          -11934.26    1130.37 -10.558  < 2e-16 ***
  Asian            566.53    1369.83   0.414 0.679188    
Amindian       -8858.57    6077.71  -1.458 0.144971    
race_oth       -7526.49    1272.49  -5.915 3.35e-09 ***
  Hispanic       -4224.82    1183.47  -3.570 0.000358 ***
  educ_hs        10592.37    1814.71   5.837 5.35e-09 ***
  educ_somecoll  22461.39    1857.67  12.091  < 2e-16 ***
  educ_college   57155.71    1830.96  31.216  < 2e-16 ***
  educ_advdeg    82766.43    1878.64  44.057  < 2e-16 ***
  ---
  Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 76760 on 46959 degrees of freedom
Multiple R-squared:   0.15,	Adjusted R-squared:  0.1498 
F-statistic: 753.6 on 11 and 46959 DF,  p-value: < 2.2e-16

require(stargazer)
stargazer(model_temp1, type = "text")

===============================================
  Dependent variable:    
  ---------------------------
  INCWAGE          
-----------------------------------------------
  AGE                        1,316.691***        
  (39.661)          

female                    -24,939.460***       
  (720.433)         

AfAm                      -11,934.250***       
  (1,130.372)        

Asian                         566.528          
(1,369.834)        

Amindian                    -8,858.569         
(6,077.710)        

race_oth                   -7,526.487***       
  (1,272.485)        

Hispanic                   -4,224.816***       
  (1,183.469)        

educ_hs                    10,592.370***       
  (1,814.709)        

educ_somecoll              22,461.390***       
  (1,857.674)        

educ_college               57,155.710***       
  (1,830.963)        

educ_advdeg                82,766.430***       
  (1,878.638)        

Constant                   -7,096.252***       
  (2,446.712)        

-----------------------------------------------
  Observations                  46,971           
R2                             0.150           
Adjusted R2                    0.150           
Residual Std. Error   76,755.980 (df = 46959)  
F Statistic         753.551*** (df = 11; 46959)
===============================================
  Note:               *p<0.1; **p<0.05; ***p<0.01

NNobs <- length(INCWAGE)
set.seed(12345)
graph_obs <- (runif(NNobs) < 0.1)
dat_graph <-subset(dat_use,graph_obs)
plot(INCWAGE ~ jitter(AGE, factor = 2), pch = 16, col = rgb(0.5, 0.5, 0.5, alpha = 0.2), ylim = c(0,150000), data = dat_graph)
to_be_predicted2 <- data.frame(AGE = 25:55, female = 1, AfAm = 0, Asian = 0, Amindian = 1, race_oth = 1, Hispanic = 1, educ_hs = 0, educ_somecoll = 0, educ_college = 1, educ_advdeg = 0)
to_be_predicted2$yhat <- predict(model_temp1, newdata = to_be_predicted2)

lines(yhat ~ AGE, data = to_be_predicted2)


In our first regression attempt we find that there is a positive correlation between incomes & wagesfor individuals aged 25 to 55. This incorporates dataset variables such that females are the focus, comparing ethnic background and levels of education.

The next linear regression will attempt to display a relationship between total income, once again focusing on females, comparing levels of education exclusively. We find that there is a positive correlation among these variables.


model_temp2 <- lm(INCTOT ~ AGE + female + educ_hs + educ_somecoll + educ_college + educ_advdeg)
summary(model_temp2)

Call:
  lm(formula = INCTOT ~ AGE + female + educ_hs + educ_somecoll + 
       educ_college + educ_advdeg)

Residuals:
  Min      1Q  Median      3Q     Max 
-156353  -35623  -12456   12374 1272927 

Coefficients:
  Estimate Std. Error t value Pr(>|t|)    
(Intercept)   -19091.37    2501.60  -7.632 2.36e-14 ***
  AGE             1568.48      42.26  37.112  < 2e-16 ***
  female        -28990.81     767.04 -37.796  < 2e-16 ***
  educ_hs        12913.12    1905.48   6.777 1.24e-11 ***
  educ_somecoll  25987.77    1941.08  13.388  < 2e-16 ***
  educ_college   64561.93    1903.13  33.924  < 2e-16 ***
  educ_advdeg    92688.79    1947.83  47.586  < 2e-16 ***
  ---
  Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 82030 on 46964 degrees of freedom
Multiple R-squared:  0.1532,	Adjusted R-squared:  0.1531 
F-statistic:  1416 on 6 and 46964 DF,  p-value: < 2.2e-16

stargazer(model_temp2, type = "text")

================================================
  Dependent variable:     
  ----------------------------
  INCTOT           
------------------------------------------------
  AGE                         1,568.480***        
  (42.264)          

female                     -28,990.810***       
  (767.038)          

educ_hs                    12,913.120***        
  (1,905.480)         

educ_somecoll              25,987.770***        
  (1,941.083)         

educ_college               64,561.930***        
  (1,903.128)         

educ_advdeg                92,688.790***        
  (1,947.827)         

Constant                   -19,091.370***       
  (2,501.604)         

------------------------------------------------
  Observations                   46,971           
R2                             0.153            
Adjusted R2                    0.153            
Residual Std. Error   82,032.490 (df = 46964)   
F Statistic         1,416.253*** (df = 6; 46964)
================================================
  Note:                *p<0.1; **p<0.05; ***p<0.01


NNobs <- length(INCTOT)
set.seed(12345)
graph_obs <- (runif(NNobs) < 0.1)
dat_graph <-subset(dat_use,graph_obs)
plot(INCTOT ~ jitter(AGE, factor = 2), pch = 16, col = rgb(0.5, 0.5, 0.5, alpha = 0.2), ylim = c(0,150000), data = dat_graph)
to_be_predicted3 <- data.frame(AGE = 25:55, female = 1, educ_hs = 0, educ_somecoll = 0, educ_college = 1, educ_advdeg = 0)
to_be_predicted3$yhat <- predict(model_temp2, newdata = to_be_predicted3)

lines(yhat ~ AGE, data = to_be_predicted3)


model_temp3 <- lm(INCTOT ~ educ_hs + educ_somecoll)
summary(model_temp3)

Our third and final regression attempts to correlate total income and lower levels of education. We find that there is neither a positive nor a negative relationship which potentially could be a computing error. I assumed that there would be a negative correlation to this.

Call:
  lm(formula = INCTOT ~ educ_hs + educ_somecoll)

Residuals:
  Min      1Q  Median      3Q     Max 
-104476  -37335  -17335   10665 1279424 

Coefficients:
  Estimate Std. Error t value Pr(>|t|)    
(Intercept)    98576.1      545.0  180.87   <2e-16 ***
  educ_hs       -49240.9      953.8  -51.63   <2e-16 ***
  educ_somecoll -40911.2     1024.4  -39.94   <2e-16 ***
  ---
  Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 86150 on 46968 degrees of freedom
Multiple R-squared:  0.06589,	Adjusted R-squared:  0.065

stargazer(model_temp3, type = "text")

================================================
  Dependent variable:     
  ----------------------------
  INCTOT           
------------------------------------------------
  educ_hs                    -49,240.930***       
  (953.761)          

educ_somecoll              -40,911.240***       
  (1,024.427)         

Constant                   98,576.100***        
  (545.001)          

------------------------------------------------
  Observations                   46,971           
R2                             0.066            
Adjusted R2                    0.066            
Residual Std. Error   86,154.940 (df = 46968)   
F Statistic         1,656.458*** (df = 2; 46968)
================================================
  
NNobs <- length(INCTOT)
set.seed(12345)
graph_obs <- (runif(NNobs) < 0.1)
dat_graph <-subset(dat_use,graph_obs)
plot(INCTOT ~ jitter(AGE, factor = 2), pch = 16, col = rgb(0.5, 0.5, 0.5, alpha = 0.2), ylim = c(0,150000), data = dat_graph)
to_be_predicted4 <- data.frame(AGE = 25:55, educ_hs = 0, educ_somecoll = 0)
to_be_predicted4$yhat <- predict(model_temp3, newdata = to_be_predicted4)

lines(yhat ~ AGE, data = to_be_predicted4)

In conclusion, we find positive correlations when we regress income & wage (Y) against Gender, Ethnic background & levels of education (X). Essentially, your dependent vs. independent variables. The P-value for variables assocaited with education seem to be uniformly 2e-16 which is far from our level of significance 0.05. This means that our null hypothesis, which is that there is no correlation, can not be rejected at that level. The larger a p-value, the less sufficient evidence there is against the null hypothesis. 